param(
  [string]$Proofs = 'C:\Users\msz\aca\Workspaces\lean_contracts\proofs',
  [string]$Scratch = 'C:\Users\msz\aca\Workspaces\lean_contracts\_c02_scratch',
  [switch]$Write
)
$target = Join-Path $Proofs 'PkgC02.lean'
$src = [System.IO.File]::ReadAllText($target)
$appendix = [System.IO.File]::ReadAllText((Join-Path $Scratch 'appendix.lean'))
$header = [System.IO.File]::ReadAllText((Join-Path $Scratch 'new_header.txt'))

# 1. replace the module header (everything before "import Contracts")
$idx = $src.IndexOf("import Contracts")
$rest = $src.Substring($idx)

# 2. drop the stale "NOT PROVIDED" comment lines about the open target
$rest = $rest.Replace("-- NOT PROVIDED (the target is open):`r`n", "")
$rest = $rest.Replace("-- NOT PROVIDED (the target is open):`n", "")
$rest = $rest.Replace("-- theorem c02_proved : C02 := fun a f g hf hg hp hq h => c02_gap a f g hf hg hp hq h", "")

# 3. update the c02_gap docstring
$oldGap = @'
/-- **The gap.**  Stated (not proved) so that the exact remaining obligation is
visible in the file.  Closing this `Prop` for all inputs is exactly what would
give `c02_proved`, and it is NOT proved here.

The symbolic audit (`audit_c02*.py`, see the module docstring) shows this is a
true statement: `c1` and `c2` lie in the ideal generated by the two scalars
`R` and `E2` above together with their first/second partial derivatives.  What is
missing is the *explicit* multiplier certificate -- the multipliers are genuine
differential expressions, not polynomials in the jets, so they were never
extracted in closed form before the time budget expired. -/
'@
$newGap = @'
/-- The same statement as `C02`, kept as a named `Prop`.  It is now *proved*:
`c02_gap_proved` at the end of this file inhabits this type, definitionally from
`c02_proved`. -/
'@
$oldGapLf = $oldGap.Replace("`r`n", "`n")
$newGapLf = $newGap.Replace("`r`n", "`n")
if ($rest.Contains($oldGap)) { $rest = $rest.Replace($oldGap, $newGap) }
elseif ($rest.Contains($oldGapLf)) { $rest = $rest.Replace($oldGapLf, $newGapLf) }
else { throw "c02_gap docstring not found" }

# 4. splice: header + (rest without final "end DLWContract") + appendix + end
$endMarker = "end DLWContract"
$pos = $rest.LastIndexOf($endMarker)
if ($pos -lt 0) { throw "end DLWContract not found" }
$body = $rest.Substring(0, $pos)
$tail = $rest.Substring($pos)

$extra = @'

/-- `c02_gap` and `C02` are the same statement; the placeholder `Prop` of the
earlier draft is therefore inhabited by the real proof. -/
theorem c02_gap_proved : c02_gap := c02_proved
'@
$out = $header + "`r`n" + $body + "`r`n" + $appendix + $extra + "`r`n" + $tail
$dest = Join-Path $Scratch 'PkgC02_merged.lean'
[System.IO.File]::WriteAllText($dest, $out)
"merged -> $dest"
if ($Write) {
  [System.IO.File]::WriteAllText($target, $out)
  "written -> $target"
}
