"""
Step 0e: the REDUCED FORMS.

`audit_c02_reduce.py` shows that c1 and c2 lie in the ideal generated by
    R, dx R, dy R, dt R, dxx R, dyy R, dtt R, dxdy R,   E2, dx E2, dy E2, dt E2
in the jet ring with Clairaut imposed.  Those are *differential consequences* of
the two smooth hypotheses:
    R = 0            <=> cbil a f g = 0
    E2 = 0           <=> cbil a f (sy g) + 2 chx f g = 0
with
    dx R = sx(R),  dy R = sy(R),  dt R = st(R),  etc.

So the certificate has the shape

    c1 = sum_q P_q * d^q R  +  sum_r Q_r * d^r E2

with P_q, Q_r smooth functions.  This script prints the *linear* part of the
dependence (which hypotheses are actually needed), by checking, for every subset
of the generators, whether c1 (resp. c2) is in the ideal of that subset.

Run:  python -u audit_c02_which.py
"""

import itertools
import sympy as sp


def build(M, amod, p):
    A, B = {}, {}
    for i, j, k in itertools.product(range(M + 1), repeat=3):
        if i + j + k <= M:
            A[(i, j, k)] = sp.Symbol('A%d%d%d' % (i, j, k))
            B[(i, j, k)] = sp.Symbol('B%d%d%d' % (i, j, k))
    a = sp.Integer(amod)

    def der(expr, var):
        sub = {}
        for idx, s in A.items():
            t = list(idx); t[var] += 1; t = tuple(t)
            if t in A:
                sub[s] = A[t]
        for idx, s in B.items():
            t = list(idx); t[var] += 1; t = tuple(t)
            if t in B:
                sub[s] = B[t]
        return sp.expand(expr.subs(sub))

    R0 = A[(2, 0, 0)] + B[(1, 0, 0)] ** 2 + B[(0, 0, 1)] + 2 * a * B[(1, 0, 0)]
    T1 = A[(0, 1, 0)] - B[(0, 1, 0)]
    Sxx2 = A[(2, 0, 0)] + B[(2, 0, 0)] + A[(2, 1, 0)] - B[(2, 1, 0)]
    Dx2 = A[(1, 0, 0)] + B[(1, 0, 0)] - A[(1, 1, 0)] + B[(1, 1, 0)]
    Dt2 = A[(0, 0, 1)] + B[(0, 0, 1)] - A[(0, 1, 1)] + B[(0, 1, 1)]
    W2c = 2 * Sxx2 + Dx2 ** 2 + 2 * Dt2 + 4 * a * Dx2
    E20 = T1 * W2c + 16 * B[(1, 0, 0)]
    c1 = (2 * B[(1, 1, 1)] + 2 * A[(3, 1, 0)] + 4 * B[(2, 0, 0)] * B[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * B[(2, 1, 0)] + 4 * a * B[(2, 1, 0)])
    c2 = (2 * A[(1, 1, 1)] + 4 * B[(2, 0, 0)] * A[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * A[(2, 1, 0)] + 2 * B[(3, 1, 0)]
          + 4 * a * A[(2, 1, 0)] - 8 * B[(2, 0, 0)])
    return der, R0, E20, c1, c2


def d(der, e, idx):
    for _ in range(idx[0]):
        e = der(e, 0)
    for _ in range(idx[1]):
        e = der(e, 1)
    for _ in range(idx[2]):
        e = der(e, 2)
    return e


def main():
    der, R0, E20, c1, c2 = build(5, 7, 32003)
    RORD = [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1),
            (2, 0, 0), (0, 2, 0), (0, 0, 2), (1, 1, 0)]
    EORD = [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)]
    Rg = {(k,): d(der, R0, k) for k in RORD}
    Eg = {(k,): d(der, E20, k) for k in EORD}

    def in_ideal(gens, f):
        vs = sorted(set().union(*[g.free_symbols for g in gens]) | f.free_symbols, key=str)
        G = sp.groebner(gens, *vs, modulus=32003, order='grevlex')
        out = G.reduce(f)
        r = out[0] if isinstance(out, tuple) else out
        r = sp.expand(r[0] if isinstance(r, list) else r)
        return r == 0

    # minimal subsets
    keys = list(Rg) + list(Eg)
    for nm, f in (('c1', c1), ('c2', c2)):
        print('==== %s ====' % nm)
        found = []
        for size in (2, 3, 4):
            for combo in itertools.combinations(keys, size):
                gs = [Rg[k] if k in Rg else Eg[k] for k in combo]
                if in_ideal(gs, f):
                    found.append(combo)
            if found:
                print('  minimal subsets of size %d:' % size)
                for c in found[:12]:
                    print('    ', [k[0] for k in c])
                if len(found) > 12:
                    print('     ... (%d total)' % len(found))
                break
        if not found:
            print('  no subset of size <= 4 works (plus Clairaut)')


if __name__ == '__main__':
    main()
