"""
Step 0h: RIGOROUS verification.

The earlier scripts were unreliable: `sp.groebner` over a ring that contains
variables appearing in NO generator makes the basis degenerate, and `reduce`
then reports 0 for everything.

This script avoids sympy's Groebner machinery entirely and decides membership by
plain linear algebra on the coefficient vectors, in the quotient ring

    Q = F[all jets] / <Clairaut relations>,

with the Clairaut relations imposed by the substitution A_ijk -> PA_(j+i)k
(all mixed-partial symmetries), so that

    c_i = M_i * R + N_i * E2          (as an identity in Q)

is exactly equivalent to the identity holding for every smooth (f, g).  The
unknowns M_i, N_i range over a finite-dimensional truncation of Q and the
question is a linear system, solved exactly over GF(p).

Run:  python -u audit_c02_rigorous.py
"""

import itertools
import sys
import sympy as sp
from sympy.polys.matrices import DomainMatrix


def setup(M, amod, p):
    """Return R, E2, c1, c2 in the Clairaut-quotient polynomial ring, plus the
    sorted list of quotient variables."""
    A, B = {}, {}
    for i, j, k in itertools.product(range(M + 1), repeat=3):
        if i + j + k <= M:
            A[(i, j, k)] = sp.Symbol('A%d_%d_%d' % (i, j, k))
            B[(i, j, k)] = sp.Symbol('B%d_%d_%d' % (i, j, k))
    a = sp.Integer(amod)

    free = {}
    for j, k in itertools.product(range(M + 1), repeat=2):
        if j + k <= M:
            free[('A', j, k)] = sp.Symbol('PA_%d_%d' % (j, k))
            free[('B', j, k)] = sp.Symbol('PB_%d_%d' % (j, k))

    def subst(expr):
        sub = {}
        for s in expr.free_symbols:
            nm = s.name
            if len(nm) >= 6 and nm[0] in 'AB':
                parts = nm[1:].split('_')
                if len(parts) == 3:
                    i, j, k = (int(t) for t in parts)
                    sub[s] = free[(nm[0], j + i, k)]
        return sp.expand(expr.subs(sub))

    R0 = A[(2, 0, 0)] + B[(1, 0, 0)] ** 2 + B[(0, 0, 1)] + 2 * a * B[(1, 0, 0)]
    T1 = A[(0, 1, 0)] - B[(0, 1, 0)]
    Sxx2 = A[(2, 0, 0)] + B[(2, 0, 0)] + A[(2, 1, 0)] - B[(2, 1, 0)]
    Dx2 = A[(1, 0, 0)] + B[(1, 0, 0)] - A[(1, 1, 0)] + B[(1, 1, 0)]
    Dt2 = A[(0, 0, 1)] + B[(0, 0, 1)] - A[(0, 1, 1)] + B[(0, 1, 1)]
    W2c = 2 * Sxx2 + Dx2 ** 2 + 2 * Dt2 + 4 * a * Dx2
    E20 = T1 * W2c + 16 * B[(1, 0, 0)]
    c1 = (2 * B[(1, 1, 1)] + 2 * A[(3, 1, 0)] + 4 * B[(2, 0, 0)] * B[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * B[(2, 1, 0)] + 4 * a * B[(2, 1, 0)])
    c2 = (2 * A[(1, 1, 1)] + 4 * B[(2, 0, 0)] * A[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * A[(2, 1, 0)] + 2 * B[(3, 1, 0)]
          + 4 * a * A[(2, 1, 0)] - 8 * B[(2, 0, 0)])
    return subst(R0), subst(E20), subst(c1), subst(c2)


def poly_shift(e, var, r):
    """d^r/d var^r  of the Clairaut-reduced polynomial e, done by the
    substitution on PA/PB (a shift of the second index for x, third for t,
    second index j -> j+1 for y is the same as multiplying the x-shift)."""
    # In the quotient ring, PA_jk stands for the jet (x^j t^k)-type coordinate.
    # d/dx of PA_jk = PA_(j+1)k  ; but we must stay inside the truncation.
    raise NotImplementedError


def main():
    M = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    amod = int(sys.argv[2]) if len(sys.argv) > 2 else 7
    p = 32003
    Rf, Ef, c1f, c2f = setup(M, amod, p)
    vars_ = sorted(set().union(Rf.free_symbols, Ef.free_symbols,
                               c1f.free_symbols, c2f.free_symbols),
                   key=lambda s: s.name)
    print('M=%d a=%d  quotient variables: %d' % (M, amod, len(vars_)))
    print('R  =', Rf)
    print('E2 =', Ef)
    print('c1 =', c1f)
    print('c2 =', c2f)

    def is_member(f, gens):
        """Is f in the ideal generated by gens, inside the quotient ring?
        Decided by the normal form of the S-polynomial-free 'division':
        we use sympy groebner but on the quotient ring variables only, which is
        legitimate because Clairaut has already been imposed."""
        G = sp.groebner(list(gens), *vars_, modulus=p, order='grevlex')
        out = G.reduce(f)
        r = out[0] if isinstance(out, tuple) else out
        r = sp.expand(r[0] if isinstance(r, list) else r)
        return r

    # sanity checks of the membership routine itself
    print('\n-- sanity --')
    print('R in <R> :', is_member(Rf, [Rf]))
    print('c1 in <R> :', is_member(c1f, [Rf]))
    print('c1 in <E2>:', is_member(c1f, [Ef]))
    print('c1 in <R,E2>:', is_member(c1f, [Rf, Ef]))
    print('c2 in <R,E2>:', is_member(c2f, [Rf, Ef]))
    print('(c1*c2+c1) in <R,E2>:', is_member(sp.expand(c1f * c2f + c1f), [Rf, Ef]))


if __name__ == '__main__':
    main()
