"""
Step 0 audit for C02.

We work in the jet space of a point for two smooth functions A, B of (x,y,t):
    A = log f + log g,   B = log f - log g       (so f,g positive  <=>  A,B arbitrary)
Then
    u = cu f g = 2 B_x ,      v = cv f g = 2 A_xy
    c1 = sy(st u) + sx(sx v) + sx(u*sy u) + 2a*sx(sy u)
    c2 = st v + sx(u*v) + sx(sx(sy u)) + 2a*sx v - 4*sx u

Hypotheses (as FUNCTIONS, hence all their derivatives vanish too):
  (I)  R := A_xx + B_x^2 + B_t + 2a B_x                       = 0
       (this is cbil a f g / (f g), the C13 quotient identity)
  (II) cbil a f (sy g) + 2 chx f g = 0
       (equivalent, given (I), to cdybil - 4 chx = 0, via C01)
       with  beta_y = (A_y - B_y)/2,  S = alpha + beta_y,  D = alpha - beta_y,
             alpha = (A+B)/2 :
       E2 := beta_y * ( S_xx + (D_x)^2 + D_t + 2a D_x ) + 2 B_x   = 0

We compute the Groebner normal form of c1, c2 modulo the ideal generated by
R and E2 together with all their partial derivatives (up to the order that fits
inside the jet truncation).  Jet symbols are indexed by the multi-index, so
Clairaut (symmetry of mixed partials) is built in.

Run:  python -u audit_c02.py
"""

import sys
import itertools
import sympy as sp


def build(M, amod, p, Mtab=None):
    """Jet symbols up to total order Mtab (>= 4); equations differentiated up to
    total order M.  Field: GF(p) with a := amod."""
    if Mtab is None:
        Mtab = max(M, 4)
    Mtable = Mtab
    A = {}
    B = {}
    for i, j, k in itertools.product(range(Mtable + 1), repeat=3):
        if i + j + k <= Mtable:
            A[(i, j, k)] = sp.Symbol('A%d%d%d' % (i, j, k))
            B[(i, j, k)] = sp.Symbol('B%d%d%d' % (i, j, k))
    a = sp.Integer(amod)

    def der(expr, var):
        """total derivative in direction var (0=x,1=y,2=t) of a jet polynomial."""
        sub = {}
        for idx, s in A.items():
            t = list(idx)
            t[var] += 1
            t = tuple(t)
            if t not in A:
                raise KeyError('jet order exceeded: A%s' % (t,))
            sub[s] = A[t]
        for idx, s in B.items():
            t = list(idx)
            t[var] += 1
            t = tuple(t)
            if t not in B:
                raise KeyError('jet order exceeded: B%s' % (t,))
            sub[s] = B[t]
        return sp.expand(expr.subs(sub))

    def ders(expr, upto):
        """expr and all its partial derivatives of TOTAL order <= upto.

        `expr` already has some total order `d0`; we iterate `upto - d0` times."""
        out = [expr]
        frontier = [expr]
        for _ in range(upto):
            nxt = []
            for e in frontier:
                for var in range(3):
                    try:
                        nxt.append(der(e, var))
                    except KeyError:
                        pass
            out.extend(nxt)
            frontier = nxt
        return out

    # (I)
    R = A[(2, 0, 0)] + B[(1, 0, 0)] ** 2 + B[(0, 0, 1)] + 2 * a * B[(1, 0, 0)]
    # (II): quotient identity for the pair (f, sy g).  We use the *unhalved*
    # combinations (allowed: halving is invertible in char != 2):
    #   2*beta_y = A01 - B01,  2*S_xx = A20+B20+A21-B21, etc.
    T1 = A[(0, 1, 0)] - B[(0, 1, 0)]
    Sxx2 = A[(2, 0, 0)] + B[(2, 0, 0)] + A[(2, 1, 0)] - B[(2, 1, 0)]
    Dx2 = A[(1, 0, 0)] + B[(1, 0, 0)] - A[(1, 1, 0)] + B[(1, 1, 0)]
    Dt2 = A[(0, 0, 1)] + B[(0, 0, 1)] - A[(0, 1, 1)] + B[(0, 1, 1)]
    #   W2 := 2*W = Sxx2 + (Dx2)^2/2 + Dt2 + 2a*Dx2 ; clear the /2:
    W2c = 2 * Sxx2 + Dx2 ** 2 + 2 * Dt2 + 4 * a * Dx2
    #   E2 = beta_y*W + 2*B10 = (1/2)*( (1/2)*T1*W2 + 4*B10 ) ; clear both halves:
    E2 = sp.expand(T1 * W2c + 16 * B[(1, 0, 0)])

    # goals
    c1 = (2 * B[(1, 1, 1)] + 2 * A[(3, 1, 0)] + 4 * B[(2, 0, 0)] * B[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * B[(2, 1, 0)] + 4 * a * B[(2, 1, 0)])
    c2 = (2 * A[(1, 1, 1)] + 4 * B[(2, 0, 0)] * A[(1, 1, 0)]
          + 4 * B[(1, 0, 0)] * A[(2, 1, 0)] + 2 * B[(3, 1, 0)]
          + 4 * a * A[(2, 1, 0)] - 8 * B[(2, 0, 0)])

    # R has total order 2; differentiate it up to total order M.
    # E2 has total order 3; differentiate it up to total order M.
    eqs = ders(R, M) + ders(E2, M)
    return A, B, c1, c2, eqs


def main():
    M = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    p = int(sys.argv[2]) if len(sys.argv) > 2 else 32003
    amod = int(sys.argv[3]) if len(sys.argv) > 3 else 7
    Mtab = int(sys.argv[4]) if len(sys.argv) > 4 else 4
    print('deriv order M=%d  table order=%d  p=%d  a=%d' % (M, Mtab, p, amod))
    A, B, c1, c2, eqs = build(M, amod, p, Mtab)
    gens = sorted(set().union(*[e.free_symbols for e in eqs]) |
                  set(c1.free_symbols) | set(c2.free_symbols), key=lambda s: s.name)
    print('variables: %d   equations: %d' % (len(gens), len(eqs)))
    G = sp.groebner(eqs, *gens, modulus=p, order='grevlex')
    print('groebner basis computed: %d elements' % len(G.exprs))
    for name, f in (('c1', c1), ('c2', c2)):
        out = G.reduce(f)
        if isinstance(out, tuple):
            r, coeffs = out
        else:
            r, coeffs = out, None
        r = sp.expand(r[0] if isinstance(r, list) else r)
        print('---- %s ----' % name)
        print('  normal form:', r)
        if r == 0:
            try:
                idx = [i for i, cf in enumerate(coeffs) if cf != 0]
                print('  nonzero cofactors on GB elements:', idx)
            except TypeError:
                print('  cofactors:', coeffs)


if __name__ == '__main__':
    main()
